services:
  - type: web
    name: voice-assistant
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools
      pip cache purge
      pip install numpy --no-build-isolation
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
